version: 2
jobs:
  build:
    working_directory: /root/jelly_shot
    docker:
      - image: elixir
    steps:
      - checkout
      - run:
          name: Install hex & rebar
          command: mix local.hex --force && mix local.rebar --force
      - run:
          name: Install Phoenix
          command: mix archive.install --force https://github.com/phoenixframework/archives/raw/master/phoenix_new.ez
      - run:
          name: Install dependencies
          command: mix deps.get
      - run:
          name: Test
          command: mix test
